# -*- mode: ruby -*-

ssh_public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQL4m2JzkMkEPm9zdWDFyJtu3D0B9IPHiMmZCuXwEJ8O7z1ZLvhcfaeJ3HoaRWnJ+ErAkJHbiRBGEJhDDOM5l7VfunEqn0BSv7Y+z7Ne9ceVJI7ltTUkN/bd372hV1WPHuGwGaccwihL6DaPcEueRd9GadZG2OCK4fncgMJ2FFa+L4j/dPLMKXN9rG62LZPvB7uutbyApMftLPUPIt5SxWpsQGC5dWA2jzMpX+MpXy2AdylazvyVh8SZ0HSXlSRuiHWJkd5/jzvqhi8ClzkZrKkHVMhdbvDUnmjn+1canhwaJxEndWvK6ctdwGYP+p5LHIsRBFvqbr8JMgkD1hdC3pv1ppfVKik05AQml4C4NWFHcuPTV9A718Tm6lk6KVOCo34fxoTvPTeUYC3D9p4OfK9txQ5MnxZuj6/l7rde38IM8umt/BlQQNp46uX3KXzktvSoD5xpis4E2gy0oT98Ayng3Jepg2Htdjx+kBspp8WUdpWiQJ9A7aut3T9Cb2rXi6CFSsDnCpYKEUBsPDRxgzw//1CTQAuy5l+XN/EYfvmE9odTAExWD3rxNOcUmAd58QcM4Xe7uRTDcaAMQEockASW/1LQKvPSb2JrGnbKBHrv31nJDAj/tGzr9aZSDpvzkrJ+24FWSmuH4IC90khFn2rNS8JX7adaQUAWsVTMgw+B2Q== udemycourse"

Vagrant.configure("2") do |config|

  # control server
  config.vm.define "control" do |control|
    control.vm.provision "file", source: "ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
    control.vm.box = "centos/7"
    control.vm.network "private_network", ip: "192.168.33.100"
    control.vm.hostname = "control"
    control.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end

  # web1 server
  config.vm.define "web1" do |web1|
    web1.vm.box = "centos/7"
    web1.vm.network "private_network", ip: "192.168.33.10"
    web1.vm.hostname = "web1"
    web1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end

  # web2 server
  config.vm.define "web2" do |web2|
    web2.vm.box = "centos/7"
    web2.vm.network "private_network", ip: "192.168.33.20"
    web2.vm.hostname = "web2"
    web2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end

  # proxy server
  config.vm.define "proxy" do |proxy|
    proxy.vm.box = "centos/7"
    proxy.vm.network "private_network", ip: "192.168.33.30"
    proxy.vm.hostname = "proxy"
    proxy.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end

  # database server
  config.vm.define "database" do |database|
    database.vm.box = "centos/7"
    database.vm.network "private_network", ip: "192.168.33.40"
    database.vm.hostname = "database"
    database.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end

  # general configuration
  config.vm.provision "shell", inline: <<-SHELL
    echo "#{ssh_public_key}" >> /home/vagrant/.ssh/authorized_keys
  SHELL
end
